server:
  port: 8090

spring:
  application:
    name: maison-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/maisondb}
    username: ${SPRING_DATASOURCE_USERNAME:maison}
    password: ${SPRING_DATASOURCE_PASSWORD:maison}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/maison/protocol/openid-connect/certs}

logging:
  level:
    org.springframework.security: DEBUG

keycloak:
  admin:
    url: ${KEYCLOAK_INTERNAL_URL:http://keycloak:8080}
    realm: ${KEYCLOAK_REALM:maison}
    username: ${KEYCLOAK_ADMIN_USER:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
